ARG BUILD_FROM=ghcr.io/home-assistant/base:latest
FROM $BUILD_FROM

# Install requirements for add-on
RUN \
  apk add --no-cache \
    python3 py3-bottle \
  && mkdir /logs

# Copy root filesystem
COPY rootfs /

RUN chmod a+x /run.sh

CMD [ "/run.sh" ]
